# -*- coding: utf-8 -*-
"""text to speech .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dRBT-GpJBdvJpGBUvnd3oFnRlReIB_Oe
"""

!pip install gTTS

from gtts import gTTS
input_text = "I like NLP and now this is machine voice"
convert = gTTS(text= input_text, lang='en', slow=False)

convert.save('audio.mp3')

input_text = "नमस्ते, आप सभी का स्वागत है"
convert = gTTS(text= input_text, lang='en', slow=False)

convert.save('audio1.mp3')

input_text = "Ich lebe in Indien"
convert = gTTS(text= input_text, lang='en', slow=False)

convert.save('audio2.mp3')

